// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4PN7RzaAYvSoe14syknJUWBfEwipxuQ',
    appId: '1:715352337545:web:daf6140a62a5d02d5e2a58',
    messagingSenderId: '715352337545',
    projectId: 'campuskart-4ce31',
    authDomain: 'campuskart-4ce31.firebaseapp.com',
    storageBucket: 'campuskart-4ce31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-6Y-AstNWehNIc0O7Kne8mDZDR4quHKo',
    appId: '1:715352337545:android:032be465f4a4c8105e2a58',
    messagingSenderId: '715352337545',
    projectId: 'campuskart-4ce31',
    storageBucket: 'campuskart-4ce31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjG0HJvNXyDFUmaVSRF1PZfCyeSqC8vuA',
    appId: '1:715352337545:ios:c0da3d0079795ed15e2a58',
    messagingSenderId: '715352337545',
    projectId: 'campuskart-4ce31',
    storageBucket: 'campuskart-4ce31.firebasestorage.app',
    iosBundleId: 'com.campuskart.campuskart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjG0HJvNXyDFUmaVSRF1PZfCyeSqC8vuA',
    appId: '1:715352337545:ios:c0da3d0079795ed15e2a58',
    messagingSenderId: '715352337545',
    projectId: 'campuskart-4ce31',
    storageBucket: 'campuskart-4ce31.firebasestorage.app',
    iosBundleId: 'com.campuskart.campuskart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4PN7RzaAYvSoe14syknJUWBfEwipxuQ',
    appId: '1:715352337545:web:f76d3b62b601047a5e2a58',
    messagingSenderId: '715352337545',
    projectId: 'campuskart-4ce31',
    authDomain: 'campuskart-4ce31.firebaseapp.com',
    storageBucket: 'campuskart-4ce31.firebasestorage.app',
  );
}
